// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Y4mqofY5pbEgMxwpa7MYtqBDtdG0smU',
    appId: '1:123760680871:web:1a97c7338aea277f02a082',
    messagingSenderId: '123760680871',
    projectId: 'women-health-companion',
    authDomain: 'women-health-companion.firebaseapp.com',
    storageBucket: 'women-health-companion.firebasestorage.app',
    measurementId: 'G-46Z4VVPXJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXUs43vTdwT3CMEDRVNXIk5Stat3hby2Y',
    appId: '1:123760680871:android:d48abffaae6eea3202a082',
    messagingSenderId: '123760680871',
    projectId: 'women-health-companion',
    storageBucket: 'women-health-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4_6-oruGm0T6hqT9LxvHpu9XURoi7j8',
    appId: '1:123760680871:ios:13beb45eb32e5c0c02a082',
    messagingSenderId: '123760680871',
    projectId: 'women-health-companion',
    storageBucket: 'women-health-companion.firebasestorage.app',
    iosBundleId: 'com.example.womenHealthPcosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo4_6-oruGm0T6hqT9LxvHpu9XURoi7j8',
    appId: '1:123760680871:ios:13beb45eb32e5c0c02a082',
    messagingSenderId: '123760680871',
    projectId: 'women-health-companion',
    storageBucket: 'women-health-companion.firebasestorage.app',
    iosBundleId: 'com.example.womenHealthPcosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Y4mqofY5pbEgMxwpa7MYtqBDtdG0smU',
    appId: '1:123760680871:web:e29481587b31b6f402a082',
    messagingSenderId: '123760680871',
    projectId: 'women-health-companion',
    authDomain: 'women-health-companion.firebaseapp.com',
    storageBucket: 'women-health-companion.firebasestorage.app',
    measurementId: 'G-54P0ZCQVN6',
  );
}
